// Package metrics provides Prometheus instrumentation for SentinelSIEM.
//
// All metrics are registered in a custom registry (not the global default)
// so tests and multiple instances don't collide. The registry is exposed
// via Handler() for mounting on an HTTP endpoint.
package metrics

import (
	"net/http"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

const namespace = "sentinel"

// Registry is the custom Prometheus registry for all SentinelSIEM metrics.
var Registry = prometheus.NewRegistry()

// ---- Ingest Pipeline ----

// EventsIngested counts raw events received by the ingest pipeline, partitioned
// by source_type (sentinel_edr, sentinel_ndr, winevt, syslog, etc.) and
// transport (http, tcp, udp, tls).
var EventsIngested = prometheus.NewCounterVec(prometheus.CounterOpts{
	Namespace: namespace,
	Subsystem: "ingest",
	Name:      "events_received_total",
	Help:      "Total raw events received by the ingest pipeline.",
}, []string{"source_type", "transport"})

// EventsIndexed counts events successfully bulk-indexed into Elasticsearch.
var EventsIndexed = prometheus.NewCounterVec(prometheus.CounterOpts{
	Namespace: namespace,
	Subsystem: "ingest",
	Name:      "events_indexed_total",
	Help:      "Total events successfully indexed into Elasticsearch.",
}, []string{"index"})

// EventsDropped counts events that failed normalization or indexing.
var EventsDropped = prometheus.NewCounterVec(prometheus.CounterOpts{
	Namespace: namespace,
	Subsystem: "ingest",
	Name:      "events_dropped_total",
	Help:      "Total events dropped due to normalization or indexing errors.",
}, []string{"reason"})

// BatchSize observes the number of events per ingest batch.
var BatchSize = prometheus.NewHistogram(prometheus.HistogramOpts{
	Namespace: namespace,
	Subsystem: "ingest",
	Name:      "batch_size",
	Help:      "Number of events per ingest batch.",
	Buckets:   []float64{1, 5, 10, 25, 50, 100, 250, 500, 1000},
})

// IndexLatency observes Elasticsearch bulk indexing latency in seconds.
var IndexLatency = prometheus.NewHistogramVec(prometheus.HistogramOpts{
	Namespace: namespace,
	Subsystem: "ingest",
	Name:      "index_duration_seconds",
	Help:      "Elasticsearch bulk index latency in seconds.",
	Buckets:   prometheus.DefBuckets,
}, []string{"index"})

// PipelineLatency observes end-to-end pipeline processing time per batch.
var PipelineLatency = prometheus.NewHistogram(prometheus.HistogramOpts{
	Namespace: namespace,
	Subsystem: "ingest",
	Name:      "pipeline_duration_seconds",
	Help:      "End-to-end pipeline processing time per batch in seconds.",
	Buckets:   prometheus.DefBuckets,
})

// InflightBatches tracks the number of batches currently being processed.
var InflightBatches = prometheus.NewGauge(prometheus.GaugeOpts{
	Namespace: namespace,
	Subsystem: "ingest",
	Name:      "inflight_batches",
	Help:      "Number of event batches currently being processed.",
})

// ---- Detection Engine ----

// AlertsGenerated counts alerts produced by the Sigma rule engine.
var AlertsGenerated = prometheus.NewCounterVec(prometheus.CounterOpts{
	Namespace: namespace,
	Subsystem: "detect",
	Name:      "alerts_generated_total",
	Help:      "Total alerts generated by the detection engine.",
}, []string{"level"})

// AlertsDeduplicated counts alerts suppressed by the dedup cache.
var AlertsDeduplicated = prometheus.NewCounter(prometheus.CounterOpts{
	Namespace: namespace,
	Subsystem: "detect",
	Name:      "alerts_deduplicated_total",
	Help:      "Total alerts suppressed by deduplication.",
})

// RuleEvalDuration observes per-event rule evaluation time in seconds.
var RuleEvalDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
	Namespace: namespace,
	Subsystem: "detect",
	Name:      "eval_duration_seconds",
	Help:      "Time to evaluate all rules against a single event.",
	Buckets:   []float64{0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1},
})

// RulesLoaded reports the current number of compiled Sigma rules.
var RulesLoaded = prometheus.NewGauge(prometheus.GaugeOpts{
	Namespace: namespace,
	Subsystem: "detect",
	Name:      "rules_loaded",
	Help:      "Number of Sigma rules currently compiled and active.",
})

// ---- Correlation State ----

// CorrelationBuckets reports the total number of active correlation buckets.
var CorrelationBuckets = prometheus.NewGauge(prometheus.GaugeOpts{
	Namespace: namespace,
	Subsystem: "correlate",
	Name:      "buckets_active",
	Help:      "Number of active correlation state buckets.",
})

// ---- Syslog ----

// SyslogConnections tracks active syslog TCP/TLS connections.
var SyslogConnections = prometheus.NewGaugeVec(prometheus.GaugeOpts{
	Namespace: namespace,
	Subsystem: "syslog",
	Name:      "connections_active",
	Help:      "Number of active syslog connections.",
}, []string{"transport"})

// SyslogMessages counts syslog messages received.
var SyslogMessages = prometheus.NewCounterVec(prometheus.CounterOpts{
	Namespace: namespace,
	Subsystem: "syslog",
	Name:      "messages_received_total",
	Help:      "Total syslog messages received.",
}, []string{"transport"})

// ---- Query API ----

// QueryLatency observes query API response time in seconds.
var QueryLatency = prometheus.NewHistogram(prometheus.HistogramOpts{
	Namespace: namespace,
	Subsystem: "query",
	Name:      "duration_seconds",
	Help:      "Query API response time in seconds.",
	Buckets:   prometheus.DefBuckets,
})

// QueryTotal counts query API requests.
var QueryTotal = prometheus.NewCounter(prometheus.CounterOpts{
	Namespace: namespace,
	Subsystem: "query",
	Name:      "requests_total",
	Help:      "Total query API requests.",
})

// ---- Auth ----

// AuthLoginAttempts counts login attempts by result.
var AuthLoginAttempts = prometheus.NewCounterVec(prometheus.CounterOpts{
	Namespace: namespace,
	Subsystem: "auth",
	Name:      "login_attempts_total",
	Help:      "Total login attempts.",
}, []string{"result"})

// AuthRateLimited counts requests rejected by rate limiting.
var AuthRateLimited = prometheus.NewCounter(prometheus.CounterOpts{
	Namespace: namespace,
	Subsystem: "auth",
	Name:      "rate_limited_total",
	Help:      "Total requests rejected by login rate limiter.",
})

func init() {
	// Register all metrics with the custom registry.
	Registry.MustRegister(
		// Ingest.
		EventsIngested,
		EventsIndexed,
		EventsDropped,
		BatchSize,
		IndexLatency,
		PipelineLatency,
		InflightBatches,

		// Detection.
		AlertsGenerated,
		AlertsDeduplicated,
		RuleEvalDuration,
		RulesLoaded,

		// Correlation.
		CorrelationBuckets,

		// Syslog.
		SyslogConnections,
		SyslogMessages,

		// Query.
		QueryLatency,
		QueryTotal,

		// Auth.
		AuthLoginAttempts,
		AuthRateLimited,
	)

	// Also register Go runtime and process collectors.
	Registry.MustRegister(
		prometheus.NewGoCollector(),
		prometheus.NewProcessCollector(prometheus.ProcessCollectorOpts{}),
	)
}

// Handler returns an http.Handler that serves Prometheus metrics.
func Handler() http.Handler {
	return promhttp.HandlerFor(Registry, promhttp.HandlerOpts{
		EnableOpenMetrics: true,
	})
}
